Swift 3
bakkenbaeck/Viewer pull request #51
Opened 2016-09-14 16:47 UTC by 3lvis

2016-09-15 07:58 UTC, Elland commented on Source/MovieContainer.swift
> +                            }) as AnyObject?
Any way we can avoid this? Or at least prettify this call? Looks so very odd here. Also possible to remove the `)`?

2016-09-15 07:59 UTC, Elland commented on Source/NSIndexPath+Contiguous.swift
> +            if section < (self as NSIndexPath).section {
Necessary to cast it?

2016-09-15 07:59 UTC, Elland commented on Source/NSIndexPath+Contiguous.swift
> +        return count + (self as NSIndexPath).row
Casting all the things! 😄

2016-09-15 08:00 UTC, Elland commented on Source/NSIndexPath+Contiguous.swift
> +        let current = (self as NSIndexPath).row * (self as NSIndexPath).section
Casts and more casts and more casts. Something wrong with migration tool or with Swift 3 as a whole?

2016-09-15 08:00 UTC, Elland commented on Source/PaginatedScrollView.swift
> +        if let controller = self.viewDataSource?.paginatedScrollView(self, controllerAtIndex: page) , controller.view.superview == nil {
Comma here makes much more sense to me. `Where` always felt too SQL filtering.

2016-09-15 08:00 UTC, Elland commented on Source/UIImage+CenteredFrame.swift
> +        var centeredFrame = CGRect.zero
I think we can remove the `CGRect` part here?

2016-09-15 08:01 UTC, Elland commented on Source/ViewerController.swift
> +    fileprivate var originalDraggedCenter = CGPoint.zero
Here as well? (Removing the `CGPoint`)

2016-09-15 08:01 UTC, Elland commented on Source/ViewerController.swift
> +        if let cachedController = self.viewerItemControllerCache.object(forKey: viewerItem.id as NSString) {
Casting necessary?

2016-09-15 08:02 UTC, Elland commented on Source/ViewerController.swift
> +            self.viewerItemControllerCache.setObject(viewerItemController, forKey: viewerItem.id as NSString)
Is this necessary?

2016-09-15 08:02 UTC, Elland commented on Source/ViewerController.swift
> +            self.viewerItemControllerCache.setObject(viewerItemController, forKey: viewerItem.id as NSString)
Casting I mean.

2016-09-15 08:02 UTC, Elland commented on Source/ViewerController.swift
> +                if let existingCell = self.collectionView.cellForItem(at: viewerItemController.indexPath! as IndexPath) {
Castings. !!.

2016-09-15 08:03 UTC, Elland commented on Source/ViewerItemController.swift
> +        let progressView = VideoProgressView(frame: CGRect.zero)
Remove `CGRect`?

2016-09-15 08:04 UTC, Elland commented on iOS/LocalCollectionController.swift
> +        cell.display(photo as! CALayer)
casting necessary here?

2016-09-15 08:04 UTC, Elland commented on iOS/LocalCollectionController.swift
>          let photo = self.photos[indexPath.row]
`indexPath as IndexPath`? Xcode Dolan Edition? 💃

2016-09-15 08:04 UTC, Elland commented on iOS/LocalCollectionController.swift
> +        self.viewerController = ViewerController(initialIndexPath: indexPath as IndexPath, collectionView: collectionView)
More casting onto itself?

2016-09-15 08:06 UTC, Elland commented on iOS/LocalCollectionController.swift
> +        if let cell = self.collectionView?.cellForItem(at: indexPath as IndexPath) as? PhotoCell, let placeholder = cell.imageView.image {
:dolan: xcode? 😄

2016-09-15 08:07 UTC, Elland commented on iOS/PopupController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: OptionsController.CellIdentifier, for: indexPath as IndexPath)
More!

2016-09-15 08:07 UTC, Elland commented on iOS/RemoteCollectionController.swift
>          let photos = self.sections[indexPath.section]
And some more...

2016-09-15 08:07 UTC, Elland commented on iOS/RemoteCollectionController.swift
> +        cell.display(photo as! CALayer)
Necessary? 💭

2016-09-15 08:08 UTC, Elland commented on iOS/RemoteCollectionController.swift
> +        self.viewerController = ViewerController(initialIndexPath: indexPath as IndexPath, collectionView: collectionView)
🔫

2016-09-15 08:08 UTC, elland requested changes
Looks pretty good. New APIs are mostly better now with 3.0. But I think migrator's been a bit dolan here. 👍

2016-09-20 07:40 UTC, 3lvis commented on Source/UIImage+CenteredFrame.swift
> +        var centeredFrame = CGRect.zero
I don't think so.

2016-09-20 07:40 UTC, 3lvis commented on Source/ViewerController.swift
> +    fileprivate var originalDraggedCenter = CGPoint.zero
I don't think that's possible as well.

2016-09-20 07:42 UTC, Elland commented on Source/ViewerController.swift
> +    fileprivate var originalDraggedCenter = CGPoint.zero
Why not? 😱

2016-09-20 07:42 UTC, 3lvis commented on Source/ViewerController.swift
> +        if let cachedController = self.viewerItemControllerCache.object(forKey: viewerItem.id as NSString) {
Looking like it, I tried to change it so NSCache gets String but it wants NSString since it conforms to protocol AnyObject.

2016-09-20 07:42 UTC, 3lvis commented on Source/ViewerController.swift
> +            self.viewerItemControllerCache.setObject(viewerItemController, forKey: viewerItem.id as NSString)
See comment above.

2016-09-20 07:43 UTC, Elland commented on Source/ViewerController.swift
> +        if let cachedController = self.viewerItemControllerCache.object(forKey: viewerItem.id as NSString) {
The whole `Any` v `AnyObject` confusion, yeah?

2016-09-20 07:45 UTC, 3lvis commented on Source/ViewerController.swift
> +    fileprivate var originalDraggedCenter = CGPoint.zero
you can only use `.zero` when variable knows the type it's expecting, since here you're declaring the type, it doesn't know it has to be a CGPoint.

2016-09-20 07:46 UTC, 3lvis commented on Source/ViewerController.swift
> +        if let cachedController = self.viewerItemControllerCache.object(forKey: viewerItem.id as NSString) {
Seems like NSCache wasn't converted to use `Any` and was left with AnyObject, making things weird.

2016-09-20 07:47 UTC, 3lvis commented on Source/ViewerItemController.swift
> +        let progressView = VideoProgressView(frame: CGRect.zero)
Here it's possible :D

2016-09-20 07:49 UTC, 3lvis commented on iOS/LocalCollectionController.swift
> +        cell.display(photo as! CALayer)
lol, display is not a reserved method on UIView. So dumb.

2016-09-20 07:50 UTC, 3lvis commented on iOS/LocalCollectionController.swift
> +        cell.display(photo as! CALayer)
lol, display is now a reserved method on UIView. So dumb.

2016-09-20 07:50 UTC, Elland commented on iOS/LocalCollectionController.swift
> +        cell.display(photo as! CALayer)
😢

2016-09-20 07:53 UTC, 3lvis commented
All comments have been addressed, @Elland. Thanks for reviewing. Anything else? 😁

2016-09-20 07:57 UTC, 3lvis reviewed
FIXED ALL THE THINGS

2016-09-20 08:01 UTC, Elland commented
Looks good to me 👍

2016-09-20 08:01 UTC, elland approved these changes

2016-09-20 08:03 UTC, merged